version: '2'
services:
  web:
    build:
      context: deployment/web
      dockerfile: Dockerfile-php-5.6
    container_name: devweb1
    ports:
      - "8080:80"
    links:
      - redis:devcache1
    volumes:
      - ./web:/var/www/html
  redis:
    build: deployment/cache
    volumes:
      - ./deployment/cache/conf:/usr/local/etc/redis.conf
    container_name: devcache1
