#
# Redis Dockerfile
#
# https://github.com/dockerfile/redis
#

# Pull base image.
FROM ubuntu

WORKDIR /app

COPY . /app
COPY conf/redis.conf /usr/local/etc/redis/redis.conf

RUN apt-get update && \
    apt-get -y upgrade && \
    apt-get install -y build-essential && \
    apt-get install -y wget && \
    wget http://download.redis.io/redis-stable.tar.gz && \
    tar xvzf redis-stable.tar.gz && \
    cd redis-stable && \
    make && \
    make install 

EXPOSE 6379

CMD ["redis-server", "/usr/local/etc/redis/redis.conf"]
